name: Calculator Workflow

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v444

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Check Files
        run: ls -lrt

      - name: Compile Calculator
        run: javac Calculator.java

      - name: Run Calculator
        run: java Calculator
